list.Add("NPCUsableWeapons", {class = "swep_ai_annabelle", title = "[NPCW] ANNABELLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_ar2", title = "[NPCW] AR2"})
list.Add("NPCUsableWeapons", {class = "swep_ai_ar3", title = "[NPCW] AR3"})
list.Add("NPCUsableWeapons", {class = "swep_ai_automaticpistol", title = "[NPCW] ALYX GUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_crossbow", title = "[NPCW] CROSSBOW"})
list.Add("NPCUsableWeapons", {class = "swep_ai_guardgun", title = "[NPCW] GUARD GUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_magnum", title = "[NPCW] MAGNUM"})
list.Add("NPCUsableWeapons", {class = "swep_ai_oicw", title = "[NPCW] OICW"})
list.Add("NPCUsableWeapons", {class = "swep_ai_pistol", title = "[NPCW] PISTOL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_rocketlauncher", title = "[NPCW] RPG"})
list.Add("NPCUsableWeapons", {class = "swep_ai_shotgun", title = "[NPCW] SHOTGUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_smg1", title = "[NPCW] SMG1"})
list.Add("NPCUsableWeapons", {class = "swep_ai_smg2", title = "[NPCW] SMG2"})
list.Add("NPCUsableWeapons", {class = "swep_ai_smg3", title = "[NPCW] SMG3"})
list.Add("NPCUsableWeapons", {class = "swep_ai_sniper", title = "[NPCW] SNIPER"})
list.Add("NPCUsableWeapons", {class = "swep_ai_taucannon", title = "[NPCW] TAU CANNON"})

list.Add("NPCUsableWeapons", {class = "swep_ai_ak47", title = "[NPCW] AK47"})
list.Add("NPCUsableWeapons", {class = "swep_ai_aug", title = "[NPCW] AUG"})
list.Add("NPCUsableWeapons", {class = "swep_ai_awp", title = "[NPCW] AWP"})
list.Add("NPCUsableWeapons", {class = "swep_ai_deagle", title = "[NPCW] DEAGLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_doublebarrel", title = "[NPCW] DOUBLE BARREL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_elite", title = "[NPCW] ELITE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_elites", title = "[NPCW] DUAL ELITES"})
list.Add("NPCUsableWeapons", {class = "swep_ai_famas", title = "[NPCW] FAMAS"})
list.Add("NPCUsableWeapons", {class = "swep_ai_fiveseven", title = "[NPCW] FIVESEVEN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_g3sg1", title = "[NPCW] G3SG1"})
list.Add("NPCUsableWeapons", {class = "swep_ai_galil", title = "[NPCW] GALIL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_glock", title = "[NPCW] GLOCK"})
list.Add("NPCUsableWeapons", {class = "swep_ai_grenadelauncher", title = "[NPCW] GRENADE LAUNCHER"})
list.Add("NPCUsableWeapons", {class = "swep_ai_hellfire", title = "[NPCW] HELLFIRE ROCKET LAUNCHER"})
list.Add("NPCUsableWeapons", {class = "swep_ai_leveraction", title = "[NPCW] LEVER ACTION"})
list.Add("NPCUsableWeapons", {class = "swep_ai_m3", title = "[NPCW] M3"})
list.Add("NPCUsableWeapons", {class = "swep_ai_m4a1", title = "[NPCW] M4A1"})
list.Add("NPCUsableWeapons", {class = "swep_ai_m4a1_s", title = "[NPCW] M4A1-S"})
list.Add("NPCUsableWeapons", {class = "swep_ai_m249", title = "[NPCW] M249"})
list.Add("NPCUsableWeapons", {class = "swep_ai_mac10", title = "[NPCW] MAC10"})
list.Add("NPCUsableWeapons", {class = "swep_ai_mgl", title = "[NPCW] MGL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_mp5", title = "[NPCW] MP5"})
list.Add("NPCUsableWeapons", {class = "swep_ai_mrl", title = "[NPCW] MRL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_p228", title = "[NPCW] P228"})
list.Add("NPCUsableWeapons", {class = "swep_ai_p90", title = "[NPCW] P90"})
list.Add("NPCUsableWeapons", {class = "swep_ai_scout", title = "[NPCW] SCOUT"})
list.Add("NPCUsableWeapons", {class = "swep_ai_sg550", title = "[NPCW] SG550"})
list.Add("NPCUsableWeapons", {class = "swep_ai_sg552", title = "[NPCW] SG552"})
list.Add("NPCUsableWeapons", {class = "swep_ai_tmp", title = "[NPCW] TMP"})
list.Add("NPCUsableWeapons", {class = "swep_ai_ump45", title = "[NPCW] UMP45"})
list.Add("NPCUsableWeapons", {class = "swep_ai_usp", title = "[NPCW] USP"})
list.Add("NPCUsableWeapons", {class = "swep_ai_usp_s", title = "[NPCW] USP-S"})
list.Add("NPCUsableWeapons", {class = "swep_ai_xm1014", title = "[NPCW] XM1014"})

list.Add("NPCUsableWeapons", {class = "swep_ai_random_all", title = "[NPCW] [RANDOM] ALL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_explosive", title = "[NPCW] [RANDOM] EXPLOSIVE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_mg", title = "[NPCW] [RANDOM] MACHINE GUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_pistol", title = "[NPCW] [RANDOM] PISTOL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_rifle", title = "[NPCW] [RANDOM] RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_shotgun", title = "[NPCW] [RANDOM] SHOTGUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_smg", title = "[NPCW] [RANDOM] SMG"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_sniper", title = "[NPCW] [RANDOM] SNIPER"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_hl2", title = "[NPCW] [RANDOM] HALF-LIFE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_random_css", title = "[NPCW] [RANDOM] COUNTER-STRIKE"})